---
swagger: "2.0"
info:
  version: 0.0.1
  title: Example application
  description: Example application server
consumes:
- application/json
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  SessionSecurity:
    description: Session authentication
    type: apiKey
    in: header
    name: Cookie
# apply all of the below endpoints with this default security
security:
  - SessionSecurity: []
paths:
  # ===========================================================================
  # auth
  # authorization related endpoints
  /api/auth/login:
    post:
      description: Login with user credential information
      tags:
        - auth
      operationId: login
      security:
        # override the default security with none
        []
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/LoginInfo"
      responses:
        200:
          description: Success, return user's detail info
          schema:
            $ref: "#/definitions/UserAccount"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /api/auth/logout:
    get:
      description: Logout current session user
      tags:
        - auth
      operationId: logout
      parameters:
        # no parameter is required
        []
      responses:
        200:
          description: Success, nothing to response
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  # ===========================================================================
  # user
  # user related endpoints
  /api/user/myself:
    get:
      description: Get current session user's detail info
      tags:
        - user
      operationId: myself
      parameters:
        # no parameter is required
        []
      responses:
        200:
          description: Success, return user's detail info
          schema:
            $ref: "#/definitions/UserAccount"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
# ===========================================================================
definitions:
  LoginInfo:
    description: Login credential info structure
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        x-nullable: false
      password:
        type: string
        x-nullable: false
  UserAccount:
    description: User account information
    type: object
    properties:
      id:
        type: integer
        format: uint32
        x-nullable: false
      firstName:
        type: string
        x-nullable: false
      lastName:
        type: string
        x-nullable: false
      department:
        type: string
        x-nullable: false
      lastLoginTime:
        type: object
        x-go-type:
          type: Time
          import:
            package: gopkg.in/guregu/null.v4
          hints:
            noValidation: true
      userLogin:
        type: object
        $ref: "#/definitions/UserLogin"
      gormModel:
        x-go-type:
          type: GormModel
          import:
            package: go-swagger-example/mymodels
          hints:
            noValidation: true
      auditModel:
        x-go-type:
          type: AuditModel
          import:
            package: go-swagger-example/mymodels
          hints:
            noValidation: true
  UserLogin:
    description: User login information
    type: object
    x-go-custom-tag: 'gorm:"foreignkey:UserID;references:id"'
    properties:
      userId:
        type: integer
        format: uint32
      loginName:
        type: string
        x-omitempty: false
      passwordHash:
        type: string
        x-omitempty: false
      email:
        type: string
        x-omitempty: false
      gormModel:
        x-go-type:
          type: GormModel
          import:
            package: go-swagger-example/mymodels
          hints:
            noValidation: true
      auditModel:
        x-go-type:
          type: AuditModel
          import:
            package: go-swagger-example/mymodels
          hints:
            noValidation: true
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
        x-nullable: false
      message:
        type: string
        x-nullable: false
